# -*- coding: utf-8 -*-
"""ROM_assembling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14cRpg3KFrTMdZ90aoWpPEhZ6lYgGpVjf
"""

from fenics import *
from ufl_legacy import nabla_div
from scipy.sparse.linalg import spsolve
from scipy.sparse import csr_matrix

L = 1
W = 0.2
rho = 1
delta = W/L
gamma = 0.4*delta**2
beta = 1.25
g = gamma

mesh = BoxMesh(Point(0, 0, 0), Point(L, W, W), 10, 3, 3)
Vh = VectorFunctionSpace(mesh, 'P', 1)

# Boundary conditions
tol = 1E-14
def clamped_boundary(x, on_boundary):
  return on_boundary and x[0] < tol
bc = DirichletBC(Vh, Constant((0, 0, 0)), clamped_boundary)

# Variational problem
u = TrialFunction(Vh)
d = u.geometric_dimension() # space dimension
v = TestFunction(Vh)
f = Constant((0, 0, -rho*g))
T = Constant((0, 0, 0))
a1 = inner(nabla_div(u)*Identity(d),nabla_grad(v))*dx
a2 = inner(nabla_grad(u) + nabla_grad(u).T,nabla_grad(v))*dx
L = dot(f, v)*dx + dot(T, v)*ds

# Assembling and adjusting
A1 = assemble(a1)
A2 = assemble(a2)
F = assemble(L)
bc.apply(A1)
bc.apply(A2)
bc.apply(F)
A1 = csr_matrix(A1.array())
A2 = csr_matrix(A2.array())
F = F[:]